---
title: "Simulation"
author: "Kallan Roan"
date: "2025-10-30"
output: html_document
---

Libraries

```{r}
library(tidyverse)

source("source/sim_mean_sd.R")

```

Preset settings

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


In R file to create comments in sim_mean_sd, Code --> Insert Roxygen Skeleton

We can "simulate" by running our function

```{r}
sim_mean_sd(n_subj = 400)
```

Can I "verify" the central limit theorem?

First with a `for` loop

```{r}
output = vector("list", length = 100)

for (i in 1:100) {
  
  output[[i]] = sim_mean_sd(30)
  
}

output |> 
  bind_rows() |> 
  ggplot(aes(x = mu_hat)) +
  geom_density()

```

Try to repeat with a map statement

```{r}
sim_results_df = 
  expand_grid(
    sample_size = c(30, 60, 90, 120),
    iter = 1:100
  ) |> 
  mutate(
    results = map(sample_size, sim_mean_sd)
  ) |> 
  unnest(results)
```










